"""Add Settings and Category models

Revision ID: 37bc79f9fa37
Revises: 99276a3fd664
Create Date: 2024-10-30 02:53:31.030811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bc79f9fa37'
down_revision = '99276a3fd664'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
